### ISSUE TITLE
When does the 228B figure come out from

### ISSUE THREAD

**Issue by shachar731945** [lukeed/clsx#42]
is it after bundling the js file?

**Comment by lukeed** [comment]
It's after building the project with [`bundt`](https://github.com/lukeed/bundt) which minifies (via terser) the varying formats and passes them thru gzip for a size calculation. This is sometimes known as "minzip" (minified + gzip) size, and is what/how people should be talking about package sizes since that's the _basic_ approach for how the bytes will be sent over the wire to browsers/clients.
